// Generated by CoffeeScript 1.9.3
(function() {
  $(document).ready(function() {
    var HEIGHT, MARGIN, RANKS, UPLOADS, WIDTH, X, Y, civdata, civs, datapoints, initalize, rankings, remaining, self, svg, to_array, to_hash, xAxis, yAxis;
    MARGIN = {
      TOP: 20,
      RIGHT: 80,
      BOTTOM: 30,
      LEFT: 50
    };
    WIDTH = 960 - MARGIN.LEFT - MARGIN.RIGHT;
    HEIGHT = 500 - MARGIN.TOP - MARGIN.BOTTOM;
    UPLOADS = 4;
    RANKS = 61;
    X = d3.scale.linear().range([0, WIDTH]).domain([0, UPLOADS]);
    Y = d3.scale.linear().range([HEIGHT, 0]).domain([1, RANKS]);
    self = this;
    xAxis = d3.svg.axis().scale(X).orient('bottom');
    yAxis = d3.svg.axis().scale(Y).orient('left');
    console.log("'Sup kid. Good on you for looking at the console. Doesn't say much, but it means you care. <3 untra");
    svg = d3.select('#linechart').append('svg').attr('width', WIDTH + MARGIN.LEFT + MARGIN.RIGHT).attr('height', HEIGHT + MARGIN.TOP + MARGIN.BOTTOM).append('g').attr('transform', 'translate(' + MARGIN.LEFT + ',' + MARGIN.TOP + ')');
    datapoints = ['civs.csv', 'civs.csv', 'civs.csv'];
    rankings = {};
    civdata = {};
    civs = [];
    remaining = 2;
    to_hash = function(data, name) {
      var d, hash, j, len;
      hash = {};
      for (j = 0, len = data.length; j < len; j++) {
        d = data[j];
        hash[d[name]] = d;
      }
      return hash;
    };
    to_array = function(data, name) {
      var arr, d, i, j, len;
      arr = [];
      for (i = j = 0, len = data.length; j < len; i = ++j) {
        d = data[i];
        arr[i] = d[name];
      }
      return arr;
    };
    initalize = function() {
      console.log('------------');
      console.log(civs);
      console.log(rankings);
      svg.append("g").attr("class", "x axis").attr("transform", "translate(0," + HEIGHT + ")").call(xAxis);
      return svg.append("g").attr("class", "y axis").call(yAxis);
    };
    d3.csv('civs.csv', function(data) {
      civdata = to_hash(data, 'name');
      civs = to_array(data, 'name');
      if (!--remaining) {
        return initalize();
      }
    });
    return d3.csv('rankings.csv', (function(_this) {
      return function(data) {
        rankings = data;
        if (!--remaining) {
          return initalize();
        }
      };
    })(this));
  });

  return;

}).call(this);
